### ISSUE TITLE
[STORY] Xperia 1/5 II (Edo) Upstream bugs

### ISSUE THREAD

**Issue by Thaodan** [SailfishOS-SonyXperia/bugs#46]
Tracking all upstream bugs here that affect us:

+ [ ]  sonyxperiadev/bug_tracker#769
+ [ ]  sonyxperiadev/bug_tracker#756
+ [x]  sonyxperiadev/bug_tracker#735
+ [x]  sonyxperiadev/bug_tracker#727
+ [ ]  sonyxperiadev/bug_tracker#771
